dataset:
    image_folder_val: '/kaggle/input/military-equipment/Dataset military equipment/images_val'
    image_folder_train: '/kaggle/input/military-equipment/Dataset military equipment/images_train'
    labels_folder_val: '/kaggle/input/military-equipment/Dataset military equipment/labels_val'
    labels_folder_train: '/kaggle/input/military-equipment/Dataset military equipment/labels_train'
    RESCALE_SIZE: 320
    MEAN: [0.5097, 0.524, 0.5099]
    STD: [0.212, 0.212, 0.237]
model:
    svs_path: "model_svs/"
    kernel_size: 3
    nkernels: 4
    output_chanels: 1
    dropout_rate: 0.15
dataloader:
    batch_size: 128
    num_workers: 0
train:
    model_name: "first_try"
    epochs: 100
    save_treshold: 15
    positive_weight: 5.0
Adam:
    learning_rate: 0.001
    beta1: 0.9 
    beta2: 0.98
    epsilon: 1e-9