dataset:
    image_folder_val: '/kaggle/input/military-equipment/Dataset military equipment/images_val'
    image_folder_train: '/kaggle/input/military-equipment/Dataset military equipment/images_train'
    labels_folder_val: '/kaggle/input/military-equipment/Dataset military equipment/labels_val'
    labels_folder_train: '/kaggle/input/military-equipment/Dataset military equipment/labels_train'
    RESCALE_SIZE: 320
    DATA_MODES: ['train', 'val', 'test']
    MEAN: [0.5097, 0.524, 0.5099]
    STD: [0.212, 0.212, 0.237]
dataloader:
    batch_size: 128
    num_workers: 4
train:
    svs_path: "model_svs/pretrain/"
    model_name: "first_try"
    epochs: 50
    save_treshold: 2
    log_path: "logs/pretrain/"
AdamW:
    learning_rate_large: 5e-4
    learning_rate_small: 5e-5
    weight_decay_large: 1e-3
    weight_decay_small: 1e-4