paths:
    pretrain_path: "/model_svs/pretrain/"
    train_path: "/model_svs/siamese_train/"
weights:
    best_pretrained_model: "second_model_ResNet18_SGE_20250112_190440_20"
    best_model: "fourht_model_ResNet18_SGE_20250120_231906_14"